spring:
  application:
    name: demo

  config:
    import: optional:file:.env[.properties]  # .env ?? ?? ??
    activate:
      on-profile: default

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # ??? ?? dev
